services:
  - type: web
    name: cook-cook
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production