services:
  - type: web
    name: cook-cook
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_ORIGIN
        # Set this to your frontend origin (e.g. https://my-app.onrender.com)
        sync: false
